### ISSUE TITLE
Broken - Radio channel buttons

### ISSUE THREAD

**Issue by iSentrie** [Benzo00/esx-radio#2]
From my tests - changing channels with a buttons don't work as intended.

https://github.com/Benzo00/esx-radio/blob/058965bb54ff6a2ae4ffbb9a0d9edf7d455f1d5d/client.lua#L155

It will just increase once and decrease once, can't go more than 1 time in one direction.

**Comment by Benzo00** [comment]
will look into this

**Comment by Mycroft-Studios** [comment]
Fixed :)
