### ISSUE TITLE
manifest -miss

### ISSUE THREAD

**Issue by Bobbbe** [Benzo00/esx-radio#5]
Hello :) am I missing an image file and a lua? (html/img/cursor.png and animation.lua)
can they be removed from the manifest or i have to add these files?
![esxradio-manifest](https://user-images.githubusercontent.com/42454593/226214143-7e2e0f1e-2b82-4b4a-a0f9-26562e5f88e3.png)

**Comment by Benzo00** [comment]
they are removed :)
